# 問題3
result1ではB()がAの引数として渡され、  
実行時のB()を利用してAを実行する。  
result2では先にB()を実行した結果をxに保持し、その後でAを実行する。  

# 問題4-1
p11ではエラースローがpromiseに渡らずにresolveが  
呼び出され、timeoutになる、あるいはf13が実行される。  
p12ではエラースローがcatchされ、f14を実行する。  

# 問題4-2
p21では例外処理が発生し、promisチェーンを通り  
f22が実行される。  
p22ではエラーがpromisの外で発生するので  
uncaught errorになる。
